# Generated by Django 5.0 on 2023-12-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=200)),
                ('date', models.DateField(max_length=200)),
                ('time', models.TimeField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('free_places', models.IntegerField()),
            ],
        ),
    ]
