# Generated by Django 5.0 on 2023-12-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_free_places_event_places'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='duration',
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=5000),
        ),
    ]
