# Generated by Django 5.0 on 2023-12-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_event_duration_alter_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(max_length=15),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=15),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(max_length=15),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=15),
        ),
    ]
