# Generated by Django 5.0 on 2023-12-21 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_event_date_alter_event_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='places',
            new_name='tickets',
        ),
    ]
